packages:
  - "."
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowedVersions:
    vite: "*"
  allowAny:
    - vite
allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.0-beta.107"
  - "@effect/platform-node@4.0.0-beta.107"
  - effect@4.0.0-beta.107
ignoredBuiltDependencies:
  - msgpackr-extract
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
