packages:
  - "."
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowedVersions:
    vite: "*"
    vitest: "*"
  allowAny:
    - vite
    - vitest
allowBuilds:
  msgpackr-extract: false
ignoredBuiltDependencies:
  - msgpackr-extract
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.1
  "@vitest/coverage-v8": 5.0.1
minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.0"
  - "@effect/platform-node@4.0.0"
  - effect@4.0.0
