packages:
  - "."
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowedVersions:
    vite: "*"
    vitest: "*"
  allowAny:
    - vite
    - vitest
allowBuilds:
  msgpackr-extract: false
ignoredBuiltDependencies:
  - msgpackr-extract
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vite-plus: 0.3.3
  vitest: 4.1.11
  "@vitest/coverage-v8": 4.1.11
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.3"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.3"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.3"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.3"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.3"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.3"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.3"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.3"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.3"
  - vite-plus@0.3.3
