export function describeCli(): unknown {
  return {
    name: "vref",
    package: "@putdotio/vref",
    version: 1,
    defaults: {
      manifest: ".vref/manifest.json",
      output: ".vref/index.html",
      serveDir: ".vref",
      host: "127.0.0.1",
      port: 4173,
    },
    output: {
      defaultInteractive: "human",
      defaultNonInteractive: "json",
      supported: ["human", "json"],
      fieldSelection: "top-level result fields with --fields",
    },
    image: {
      outputFormat: "webp",
      outputExtension: ".webp",
      lossless: true,
      lossyFlag: "--quality",
      sourceFormats: [".jpg", ".jpeg", ".png", ".webp"],
      encoder: "sharp",
      notes: [
        "vref encodes webp only; --quality switches from lossless to lossy webp",
        "webp sources are copied verbatim unless --quality forces a re-encode",
        "viewport defaults to the source pixel size; pass viewport in --json for retina captures",
        "manifest entries may still reference legacy .jpg, .jpeg, and .png assets",
      ],
    },
    automation: {
      defaultNonInteractiveOutput: "json",
      dryRunForMutations: true,
      fieldSelection: true,
      pathSandboxing: true,
      rawJsonInput: true,
      schemaIntrospection: true,
      skillPath: "skills/vref/SKILL.md",
      untrustedTextAnnotations: true,
      untrustedTextPaths: [
        "result.screenshot.title",
        "result.screenshot.group",
        "result.screenshot.platform",
        "result.screenshot.device",
        "result.screenshot.tags[]",
        "result.screenshot.notes[]",
      ],
    },
    commands: {
      build: {
        description: "Validate a visual reference manifest and render a static gallery.",
        mutates: [".vref/index.html"],
        options: {
          manifest: { type: "string", default: ".vref/manifest.json" },
          out: {
            type: "string",
            flags: ["--out", "--output-path"],
            default: ".vref/index.html",
          },
          check: {
            type: "boolean",
            flags: ["--check", "--dry-run"],
            default: false,
            description: "Validate without writing index.html.",
          },
          outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
          fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
        },
      },
      validate: {
        description: "Validate a visual reference manifest and screenshot assets without writing.",
        mutates: [],
        options: {
          manifest: { type: "string", default: ".vref/manifest.json" },
          outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
          fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
        },
      },
      serve: {
        description: "Serve the visual reference directory over a local HTTP server.",
        mutates: [],
        options: {
          dir: { type: "string", default: ".vref" },
          host: { type: "string", default: "127.0.0.1" },
          port: { type: "number", default: 4173 },
          outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
          fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
        },
      },
      screenshot: {
        add: {
          description:
            "Encode a captured source image to webp, write it under .vref/screenshots/, and append its manifest entry.",
          mutates: [".vref/manifest.json", ".vref/screenshots/*.webp"],
          positionals: [
            { name: "source", required: true, description: "Path to the captured image." },
          ],
          options: {
            manifest: { type: "string", default: ".vref/manifest.json" },
            json: {
              flag: "--json",
              type: "object",
              schema: "screenshotDraft",
              required: true,
            },
            quality: {
              flag: "--quality",
              type: "number",
              range: [1, 100],
              description: "Encode lossy webp at this quality instead of lossless.",
            },
            force: {
              type: "boolean",
              flags: ["--force"],
              default: false,
              description: "Replace an existing screenshot asset.",
            },
            dryRun: {
              type: "boolean",
              flags: ["--dry-run", "--check"],
              default: false,
              description: "Encode and validate without writing the asset or the manifest.",
            },
            outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
            fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
          },
        },
      },
      convert: {
        description:
          "Re-encode non-webp manifest assets to webp and rewrite their manifest entries.",
        mutates: [".vref/manifest.json", ".vref/screenshots/*"],
        notes: [
          "savedBytes is bytes removed minus bytes written; it is negative when the tree grows, including under --keep-source",
          "re-encoding a lossy jpeg to lossless webp grows it, so pass --quality for jpeg sources",
        ],
        options: {
          manifest: { type: "string", default: ".vref/manifest.json" },
          only: {
            flag: "--only",
            type: "string",
            description: "Comma-separated screenshot ids to convert.",
          },
          quality: {
            flag: "--quality",
            type: "number",
            range: [1, 100],
            description: "Encode lossy webp at this quality instead of lossless.",
          },
          keepSource: {
            type: "boolean",
            flags: ["--keep-source"],
            default: false,
            description: "Keep the original asset after converting.",
          },
          force: {
            type: "boolean",
            flags: ["--force"],
            default: false,
            description: "Replace an existing webp asset.",
          },
          dryRun: {
            type: "boolean",
            flags: ["--dry-run", "--check"],
            default: false,
            description: "Report the conversion plan without writing files.",
          },
          outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
          fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
        },
      },
      manifest: {
        add: {
          description: "Append one screenshot manifest entry from raw JSON.",
          mutates: [".vref/manifest.json"],
          options: {
            manifest: { type: "string", default: ".vref/manifest.json" },
            json: {
              flag: "--json",
              type: "object",
              schema: "manifest.screenshots[]",
              required: true,
            },
            dryRun: {
              type: "boolean",
              flags: ["--dry-run", "--check"],
              default: false,
              description: "Validate and preview the manifest append without writing.",
            },
            outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
            fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
          },
        },
      },
      describe: {
        description: "Print command and manifest schema metadata.",
        mutates: [],
        options: {
          outputFormat: { flag: "--output", values: ["human", "json"], default: "human" },
          fields: { flag: "--fields", type: "string", scope: "top-level result fields" },
        },
      },
    },
    manifest: {
      version: 1,
      path: ".vref/manifest.json",
      requiredFields: ["version", "title", "description", "updatedAt", "screenshots"],
      screenshotRequiredFields: [
        "id",
        "title",
        "group",
        "platform",
        "device",
        "viewport",
        "file",
        "capturedAt",
        "sizeBytes",
        "tags",
        "notes",
      ],
      fields: {
        version: { type: "literal", value: 1, required: true },
        title: { type: "string", required: true, minLength: 1 },
        description: { type: "string", required: true, minLength: 1 },
        updatedAt: { type: "string", format: "date-time", required: true },
        screenshots: {
          type: "array",
          required: true,
          minItems: 0,
          items: {
            type: "object",
            requiredFields: [
              "id",
              "title",
              "group",
              "platform",
              "device",
              "viewport",
              "file",
              "capturedAt",
              "sizeBytes",
              "tags",
              "notes",
            ],
            fields: {
              id: {
                type: "string",
                pattern: "^[a-z0-9][a-z0-9._-]*$",
                required: true,
              },
              title: { type: "string", required: true, minLength: 1 },
              group: { type: "string", required: true, minLength: 1 },
              platform: { type: "string", required: true, minLength: 1 },
              device: { type: "string", required: true, minLength: 1 },
              viewport: {
                type: "object",
                required: true,
                requiredFields: ["width", "height"],
                fields: {
                  width: { type: "number", required: true, minimumExclusive: 0 },
                  height: { type: "number", required: true, minimumExclusive: 0 },
                },
              },
              file: {
                type: "string",
                required: true,
                relativeTo: "manifest directory",
                allowedExtensions: [".jpg", ".jpeg", ".png", ".webp"],
              },
              capturedAt: { type: "string", format: "date-time", required: true },
              sizeBytes: { type: "number", required: true, minimumExclusive: 0 },
              tags: {
                type: "array",
                required: true,
                items: { type: "string", pattern: "^[a-z0-9][a-z0-9._-]*$" },
              },
              notes: { type: "array", required: true, items: { type: "string" } },
            },
          },
        },
      },
      screenshotDraft: {
        usedBy: "vref screenshot add --json",
        requiredFields: ["id", "title", "group", "platform", "device"],
        optionalFields: ["viewport", "file", "capturedAt", "tags", "notes"],
        derivedFields: {
          file: "screenshots/<id>.webp when omitted; must end in .webp",
          sizeBytes: "always the encoded webp byte length",
          viewport: "source image pixel dimensions when omitted",
          capturedAt: "source file modification time when omitted",
        },
      },
      pathRules: [
        "screenshot file paths are relative to the manifest directory",
        "absolute paths are rejected",
        "path traversal and encoded traversal are rejected",
        "query strings and hash fragments are rejected",
        "control characters are rejected",
        "URL schemes and drive prefixes are rejected",
        "symlinked screenshot assets are rejected",
      ],
    },
  };
}
